# Development environment configuration
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:shiska_db
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USERNAME:your-mailtrap-username}
    password: ${MAIL_PASSWORD:your-mailtrap-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: development
    # active: production
    # active: test

# JWT Configuration
app:
  jwt:
    secret: devSecretKeyForLocalDevelopmentOnly
    expiration: 86400000 # 24 hours

# Logging Configuration
logging:
  level:
    root: INFO
    com.shiska.restaurant: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# File Upload Configuration
file:
  upload-dir: ./uploads

